### ISSUE TITLE
Mapping Parsing Exception in vulnerability.score.temporal field

### ISSUE THREAD

**Issue by rdrgporto** [tesla-consulting/qualysbeat#2]
Hi, everyone

**Version**: QualysBeat_v2
**Elasticsearch**: 7.9.2
**Kibana**: 7.9.2

Sometimes, **QualysBeat log** shows an error about **mapping parsing exception**:

```
 {"type":"mapper_parsing_exception","reason":"failed to parse field [vulnerability.score.temporal] of type [float] in document with id 'SFFBAXgBuRfaIDRDpSiw'. Preview of field's value: '4.3 (E:POC/RL:W/RC:C)'","caused_by":{"type":"number_format_exception","reason":"For input string: \"4.3 (E:POC/RL:W/RC:C)\""}}
```

Here you are my configuration:

```
qualysbeat:
  # Defines how often an event is sent to the output
  period: 1m
  api: "https://qualysapi.qualys.eu/api/2.0/fo/scan/"
  user: "<username>"
  password: "<password>"
  cliente: "*"

# ---------------------------- Elasticsearch Output ----------------------------
output.elasticsearch:
  hosts: ["localhost:9200"]
```

Maybe, set **vulnerability.score.temporal** field as **keyword** ?

Thanks in advance,

Rodrigo
